- platform: "mqtt"
  name: "Bedroom Temperature"
  unique_id: "bedroom_temperature"
  state_topic: "nodemcu2mqtt/nodemcu-si7021"
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_template: "{{ value_json.temperature }}"

- platform: "mqtt"
  name: "Bedroom Humidity"
  unique_id: "bedroom_humidity"
  state_topic: "nodemcu2mqtt/nodemcu-si7021"
  unit_of_measurement: "%"
  device_class: "humidity"
  value_template: "{{ value_json.humidity }}"